services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/Entity/'
      - '../src/Kernel.php'

  App\Security\JwtTokenManager:
    arguments:
      $secret: '%env(JWT_SECRET)%'
